language: node_js
node_js:
- lts/*
before_install:
- openssl aes-256-cbc -K $encrypted_5c70186c1125_key -iv $encrypted_5c70186c1125_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- sed -i "s/bolaget/$SYSTEMBOLAGETAPIKEY/g" app.yaml
- cat app.yaml
deploy:
  provider: gae
  keyfile: graphqlbolaget-cb1b1c754470.json
  project: graphqlbolaget
  on: master
